### PR TITLE
Add libffi

### PR DESCRIPTION
**Pull request by triplef**
This adds a build phase for libffi.

It currently fails during `make install` with the following error:
```
 ../install-sh -c -d '/Users/me/Library/Android/GNUstep/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libffi.la '/Users/me/Library/Android/GNUstep/lib'
libtool: install: /usr/bin/install -c .libs/libffi.so /Users/me/Library/Android/GNUstep/lib/libffi.so
install: .libs/libffi.so: No such file or directory
make[3]: *** [install-toolexeclibLTLIBRARIES] Error 71
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

I’d appreciate any thoughts on how this can be resolved. See also https://github.com/libffi/libffi/issues/476.

### CODE REVIEW

**Comment by ivucica** [comment]
I'm all for enabling the functionality that depends on libffi, but I'm curious, what are you actively depending on?

**Comment by triplef** [comment]
Hey @ivucica, not sure I understand the question... do you mean what the toolchain as a whole depends on? That should be documented in the readme.

**Comment by ivucica** [comment]
I am asking why do you need libffi for GNUstep; which GNUstep functionality are you actively using which depends on libffi?

**Comment by triplef** [comment]
The main thing I came across was support for NSInvocation, which is used in various places in GNUstep internally, e.g. in NSRunLoop (hence this [patch](https://github.com/gnustep/tools-android/blob/master/patches/gnustep-base-disable-runloop-housekeeping-invocation.patch) to get NSRunLoop to not crash), and also for KVO support in mutable collection classes. It’s also used to support arbitrary structs in KVO, although I don’t think we would need that for our use case.

I appreciate your help with this.

**Comment by triplef** [comment]
I ended up copying libffi.a manually instead of using `make install`.

**Comment by ivucica** [comment]
@triplef Note that this means you've built it statically. If that works for you, then there should be no libffi.so in play at all.

**Comment by ivucica** [comment]
Nevermind, I see what you mean (you invoked this in the merged `.sh` _in place of_ running `make install`). I like this. :+1:

**Comment by triplef** [comment]
Yep thanks, I figured this out too shortly after I wrote this: https://github.com/gnustep/tools-android/commit/54b6d26a98e06d90db74feffead67164d060f205 🚀

**Pull request merged**
